// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yujejvnssywgkppsgmjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1amVqdm5zc3l3Z2twcHNnbWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODAzODAsImV4cCI6MjA3Mjc1NjM4MH0.RGqnril1IyoEDoNSVRPXpg_fj9e7-6QQJojAynRHIC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});